# Dependencies
markdown: kramdown
# Permalinks
permalink:        pretty

# Setup
title:            wguss
tagline:          'Artificially intelligent mathematician.'
description:      'I do machine learning, mathematics, and <a href="https://thepelicants.bandcamp.com/">music</a>.'
baseurl:          http://wguss.ml

author:
  name:           'William Guss'
  url:            "http://wguss.ml/"


# Custom vars
version:          2.1.0

github:       
  repo:           https://github.com/madcowd

gems:
  - jekyll-redirect-from



app:
  authors:
    wguss:
      name: 'William Guss'
      url: 'http://wguss.ml'
    rsalkhu:
      name: 'Ruslan Salakhutdinov'
      url: 'http://www.cs.cmu.edu/~rsalakhu/'
